#!/usr/bin/python

import imaplib
obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
obj.login('drfall@trioptimum.com','a16qwt32q12zxc24')
obj.select()
print(len(obj.search(None, 'UnSeen')[1][0].split()))
